openapi: 3.1.0
x-stoplight:
  id: b5jf8q8ypnn00
info:
  title: Hunter
  version: '1.0'
  description: Методы для охотников
servers:
  - url: 'http://localhost:3000'
paths:
  /tickets:
    parameters: []
    post:
      summary: Заявка на охотбилет
      operationId: post-ticket
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: 'stoplight://resources/overrides/rTRS9fcmHNM'
              examples: {}
      x-stoplight:
        id: 18l6doir5l5ea
      description: Подать заявление на выдачу охотничьего билета
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                applicant:
                  x-stoplight:
                    id: h5bcbdahegycn
                  oneOf:
                    - $ref: 'stoplight://resources/overrides/7Hqxdx1KaNE'
                      x-stoplight:
                        id: d7r2j5pfajm57
                    - type: string
                      x-stoplight:
                        id: 3jubg4qzv87rn
                      format: uuid
                issueOffice:
                  type: string
                  x-stoplight:
                    id: cgf2fjg898ma1
                  format: uuid
                huntMinimum:
                  type: boolean
                  x-stoplight:
                    id: ol4nf4j42qbko
              required:
                - applicant
                - issueOffice
                - huntMinimum
    get:
      summary: Список охотбилетов
      operationId: get-tickets
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        x-stoplight:
                          id: vjuv3em1k8tl0
                        items:
                          $ref: ../models/ticket-schema.json
                          x-stoplight:
                            id: j7n5h9mj8cuqk
                      registry:
                        type: string
                        const: ticket
                        x-stoplight:
                          id: 0gqrvqxz30890
                  - $ref: '#/components/responses/listOfEntries'
                    x-stoplight:
                      id: gfb1birxx6u5t
              examples: {}
          description: Список охотбилетов
      x-stoplight:
        id: yuaqqqesg7wwd
      description: Получить пагинированный список охотбилетов
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/getListOfEntries'
  '/tickets/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: UUID или серияномер билета
    get:
      summary: Получить охотбилет по ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/ticket-schema.json
              examples: {}
      operationId: get-ticket-byid
      x-stoplight:
        id: nkv23tapfiv7c
      parameters: []
components:
  schemas: {}
  requestBodies:
    getListOfEntries:
      content:
        application/json:
          schema:
            type: object
            properties:
              filter:
                type: object
                x-stoplight:
                  id: pbp11bepz6mbm
              sort:
                type: object
                x-stoplight:
                  id: 2y8t2lu9chwgb
              startCursor:
                type: string
                x-stoplight:
                  id: qv211ofkvz7qt
                format: uuid
              pageSize:
                type: string
                x-stoplight:
                  id: d4yqmaj5b52xz
      description: Форма запроса списка записей из реестра
    getListOfVersionedEntries:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/requestBodies/getListOfEntries'
              - type: object
                x-stoplight:
                  id: b2a98kxicp9gl
                properties:
                  date:
                    type: string
                    x-stoplight:
                      id: d4d8iskr8kwwm
                    format: date-time
  responses:
    listOfEntries:
      description: Формат ответа на получение списка записей реестра
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                x-stoplight:
                  id: afczypl1vnv6i
                items:
                  $ref: 'stoplight://resources/overrides/hM6pcYZZMrM'
                  x-stoplight:
                    id: e3vb9v4kytq7b
              nextCursor:
                type: string
                x-stoplight:
                  id: kkq20m2bpdtc7
                format: uuid
              hasMore:
                type: boolean
                x-stoplight:
                  id: 7gbbs1s596mf3
              registry:
                x-stoplight:
                  id: c4sf56fmfsmje
                type: string
          examples: {}
