openapi: 3.1.0
x-stoplight:
  id: b5jf8q8ypnn00
info:
  title: Hunter
  version: '1.0'
  description: Методы для охотников
servers:
  - url: 'http://localhost:3000'
paths:
  /tickets:
    parameters: []
    post:
      summary: Заявка на охотбилет
      operationId: post-ticket
      responses:
        '201':
          $ref: '#/components/responses/ticketApp'
      x-stoplight:
        id: 18l6doir5l5ea
      description: Подать заявление на выдачу охотничьего билета
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/ticket/ticket-app-schema-min.json
    get:
      summary: Список охотбилетов
      operationId: get-tickets
      responses:
        '200':
          $ref: '#/components/responses/listOfTickets'
      x-stoplight:
        id: yuaqqqesg7wwd
      description: Получить пагинированный список охотбилетов
      requestBody:
        $ref: '#/components/requestBodies/getListOfEntries'
  '/tickets/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: UUID или серияномер билета
    get:
      summary: Получить охотбилет по ID
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/ticket'
      operationId: get-ticket-byid
      x-stoplight:
        id: nkv23tapfiv7c
      parameters: []
components:
  schemas: {}
  requestBodies:
    getListOfEntries:
      content:
        application/json:
          schema:
            type: object
            properties:
              filter:
                type: object
                x-stoplight:
                  id: pbp11bepz6mbm
              sort:
                type: object
                x-stoplight:
                  id: 2y8t2lu9chwgb
              startCursor:
                type: string
                x-stoplight:
                  id: qv211ofkvz7qt
                format: uuid
              pageSize:
                type: string
                x-stoplight:
                  id: d4yqmaj5b52xz
              date:
                type: string
                x-stoplight:
                  id: bxoxec607a2nz
                format: uuid
      description: Форма запроса списка записей из реестра
  responses:
    listOfTickets:
      description: |
        Формат ответа на получение списка билетов
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../models/common/listOfEntries.json
              - type: object
                x-stoplight:
                  id: bkzrj0592v5sv
                properties:
                  results:
                    type: array
                    x-stoplight:
                      id: ulfq8apx51oo0
                    items:
                      $ref: ../models/ticket/ticket-schema.json
                      x-stoplight:
                        id: t00cwv2d8u8t7
    ticket:
      description: Форма охотбилета
      content:
        application/json:
          schema:
            $ref: ../models/ticket/ticket-schema.json
    ticketApp:
      description: |
        Форма заявки на охотбилет
      content:
        application/json:
          schema:
            $ref: ../models/ticket/ticket-app-schema-real.json
